import assert from "node:assert/strict";
import { COMBAT_STAGE_ACTOR_ANCHORS, COMBAT_STAGE_CAMERA_ANCHORS, COMBAT_STAGE_DEPTH, COMBAT_STAGE_LAYERS, CombatStage, createCombatActor, createCombatStageActors } from "./combat_stage.js";
const stage = new CombatStage({ actors: createCombatStageActors({ batter: { id: "bw001", name: "Aiko Hanamori" }, enemy: { id: "enemy-01", name: "Enemy Fixture" } }) });
const snapshot = stage.getState();
assert.equal(snapshot.contract, "COMBAT_STAGE_2_5D");
assert.equal(snapshot.presentationOnly, true);
assert.equal(snapshot.actorCount, 5);
assert.equal(snapshot.playerCount, 4);
assert.equal(snapshot.enemyCount, 1);
assert.deepEqual(snapshot.depthModel, ["FAR", "MID", "NEAR"]);
assert.ok(COMBAT_STAGE_LAYERS.every((layer) => snapshot.layers.some((entry) => entry.id === layer)));
assert.deepEqual(COMBAT_STAGE_CAMERA_ANCHORS, snapshot.cameraAnchors);
assert.deepEqual(COMBAT_STAGE_ACTOR_ANCHORS, snapshot.actorAnchors);
assert.deepEqual(Object.keys(snapshot.zones), ["PLAYER_ZONE", "ENEMY_ZONE"]);
assert.equal(stage.getActor("bw001").kind, "CHARACTER");
assert.equal(stage.getActor("fixture-player-02").kind, "FIXTURE");
assert.equal(stage.getActor("enemy-01").team, "ENEMY");
for (const name of COMBAT_STAGE_ACTOR_ANCHORS) assert.ok(stage.getActorAnchor("bw001", name), name);
const playerFocus = stage.getCameraAnchor("PLAYER_FOCUS", { actorId: "bw001" });
const enemyFocus = stage.getCameraAnchor("ENEMY_FOCUS", { actorId: "enemy-01" });
assert.equal(playerFocus.source, "ACTOR"); assert.equal(playerFocus.actorId, "bw001");
assert.equal(enemyFocus.source, "ACTOR"); assert.equal(enemyFocus.actorId, "enemy-01");
const transform = stage.resolveActorTransform("bw001", { width: 720, height: 1280 });
assert.ok(transform.x > 0 && transform.y > 0); assert.equal(transform.depth, "MID");
const custom = createCombatActor({ actorId: "far-test", position: { x: 0.5, y: 0.4 }, depth: COMBAT_STAGE_DEPTH.FAR });
assert.equal(custom.depth, "FAR"); assert.ok(custom.scale < 1);
const before = JSON.stringify(stage.getActor("bw001")); stage.setSelectedActor("bw001"); assert.equal(JSON.stringify(stage.getActor("bw001")), before);
console.log("T078 combat stage contract: PASS");
