import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
const root=path.resolve("webapp");
const economy=fs.readFileSync(path.join(root,"js/economy.js"),"utf8");
const shop=fs.readFileSync(path.join(root,"js/shop_ui.js"),"utf8");
const combat=fs.readFileSync(path.join(root,"js/combat.js"),"utf8");
const app=fs.readFileSync(path.join(root,"js/app.js"),"utf8");
const index=fs.readFileSync(path.join(root,"index.html"),"utf8");
const css=fs.readFileSync(path.join(root,"css/styles.css"),"utf8");
const sw=fs.readFileSync(path.join(root,"sw.js"),"utf8");
assert.ok(economy.includes("EconomyBoostManager"));
assert.ok(economy.includes("consumeTimingTurn")&&economy.includes("consumeRewardTurn"));
assert.ok(shop.includes("requestScrapPurchase")&&shop.includes("Telegram Stars"));
assert.ok(combat.includes("getEconomyBoosts")&&combat.includes("timingGraceMs"));
assert.ok(combat.includes("base_amount")&&combat.includes("multiplier"));
assert.ok(app.includes("ShopUI")&&app.includes("shopUI.open()"));
assert.ok(index.includes('id="shop-panel"')&&index.includes('id="hud-scrap"'));
assert.ok(css.includes(".shop-panel")&&css.includes(".shop-item"));
assert.ok(sw.includes("./js/shop_ui.js"));
console.log("OK P18 Economy & Shop integration");
