import assert from "node:assert/strict";
import fs from "node:fs";
import {HomeView,buildHomeViewModel} from "./home_view.js";
import {CharacterDetailView,buildCharacterDetailViewModel} from "./character_detail_view.js";
import {MainMenu,VIEWS} from "./main_menu.js";
const snapshot={inventory:{characters:{bw001:{quantity:3,unlocked:true},bw002:{quantity:1,unlocked:true}}},currencies:{SCRAP:12000},roster:{activeBatter:"bw001",supports:["bw002",null]}};
const character={character_id:"bw001",canonical:{display_name:"Aiko Hanamori",rarity:"R",position:"3B",specialization:"power",stats:{power:72,contact:64,speed:51},identity:{play_identity:"big_swing_threat"}}};
const progression={level:12,star_rank:2,duplicate_count:3};
const model=buildHomeViewModel({snapshot,activeCharacter:character,roster:snapshot.roster,progression,getCharacter:id=>id==="bw002"?{character_id:"bw002",canonical:{display_name:"Reina Kurose"}}:null});
assert.equal(model.character.name,"Aiko Hanamori");assert.equal(model.character.level,12);assert.equal(model.character.starRank,2);assert.equal(model.resources.scrap,12000);assert.equal(model.roster.supports[0].name,"Reina Kurose");assert.equal(model.ownedCharacterCount,2);assert.match(model.character.assetPath,/bw001--normal\.jpg$/);
class N{constructor(action=null){this.dataset=action?{homeAction:action}:{};this.textContent="";this.hidden=false;this.src="";this.alt="";this.onerror=null;this.listeners={};this.classList={toggle(){}}}addEventListener(t,f){this.listeners[t]=f}click(){this.listeners.click?.()}}
class R{constructor(actions){this.nodes=new Map(["#home-character-detail-open","#home-character-name","#home-character-rarity","#home-character-role","#home-character-play-identity","#home-character-level","#home-character-stars","#home-character-duplicates","#home-stat-power","#home-stat-contact","#home-stat-speed","#home-squad-batter","#home-squad-support-0","#home-squad-support-1","#home-owned-count","#home-scrap","#home-character-art","#home-character-empty"].map(s=>[s,new N()]));this.actions=actions.map(a=>new N(a))}querySelector(s){return this.nodes.get(s)||null}querySelectorAll(s){return s==="[data-home-action]"?this.actions:[]}}
const nav=[],root=new R(["combat","dex","roster","locker","gacha"]);let inspected=null;new HomeView({root,getSnapshot:()=>snapshot,getActiveCharacter:()=>character,getRoster:()=>snapshot.roster,getProgression:()=>progression,getCharacter:id=>id==="bw002"?{character_id:"bw002",canonical:{display_name:"Reina Kurose"}}:null,onNavigate:v=>nav.push(v),onInspect:id=>{inspected=id}}).mount();assert.equal(root.querySelector("#home-character-name").textContent,"Aiko Hanamori");assert.equal(root.querySelector("#home-scrap").textContent,"12,000");root.actions.forEach(n=>n.click());assert.deepEqual(nav,["combat","dex","roster","locker","gacha"]);root.querySelector("#home-character-detail-open").click();assert.equal(inspected,"bw001");
const empty=new R([]);new HomeView({root:empty}).mount();assert.equal(empty.querySelector("#home-character-name").textContent,"SIN PERSONAJE ACTIVO");assert.equal(empty.querySelector("#home-character-art").hidden,true);assert.equal(empty.querySelector("#home-character-empty").hidden,false);
const menu=new MainMenu();assert.equal(VIEWS[0],"home");assert.equal(menu.activeView,"home");assert.equal(menu.navigate("invalid"),"home");
const app=fs.readFileSync(new URL("./app.js",import.meta.url),"utf8"),index=fs.readFileSync(new URL("../index.html",import.meta.url),"utf8"),home=fs.readFileSync(new URL("./home_view.js",import.meta.url),"utf8");assert.match(app,/mainMenu\.navigate\(initialView\)/);assert.match(app,/kytos_demo/);assert.match(app,/narrative_test/);assert.match(index,/id="home-view"/);assert.doesNotMatch(home,/waifu_database|waifus_config|SaveSystem|localStorage/);
const detailModel=buildCharacterDetailViewModel({character:{character_id:"bw002",canonical:{display_name:"Reina Kurose",rarity:"SSR",position:"P",specialization:"pitcher",element:"ice",faction:"shadow_magic",stats:{power:52,contact:58,speed:49,pitch:82,control:79,defense:70,critical:13,stamina:86},identity:{archetype:"refined_ice_strategist",style_tags:["elegant","controlled"],play_identity:"tempo_control",story_status:"story_seed",story_hook:"Una pitcher impecable descubre que controlar el ritmo del rival importa tanto como lanzar fuerte.",signature_action_ids:["tempo_freeze"],skill_roles:["power_down","combination"]}}},inventoryEntry:{quantity:1,unlocked:true},progression:{level:12,star_rank:1,duplicate_count:1},roster:{activeBatter:"bw002"},currencies:{scrap:5000,fragments:4},canUpgrade:true,upgradeCost:{scrap:1000,fragments:1,next_level:13}});assert.equal(detailModel.name,"Reina Kurose");assert.equal(detailModel.identity.playIdentity,"TEMPO CONTROL");assert.equal(detailModel.identity.storyHook.includes("pitcher impecable"),true);assert.equal(detailModel.relationship.status,"ACTIVE IN YOUR SQUAD");assert.equal(detailModel.progression.canUpgrade,true);assert.equal(detailModel.stats.pitch,82);
const detailSource=fs.readFileSync(new URL("./character_detail_view.js",import.meta.url),"utf8");assert.doesNotMatch(detailSource,/localStorage|SaveSystem|waifu_database|waifus_config/);assert.match(detailSource,/storyHook|styleTags|signatureActionIds|canUpgrade|onUpgrade|onUse/);assert.match(app,/CharacterDetailView/);
console.log("[home-view] model, render, actions, fallback, MainMenu and legacy boundary passed");
