const ACTION_TARGETS=Object.freeze({combat:"combat",dex:"dex",roster:"roster",locker:"locker",gacha:"gacha"});
function int(value,fallback=0){const n=Number(value);return Number.isInteger(n)&&n>=0?n:fallback}
function nameOf(c,fallback="NO ACTIVE CHARACTER"){return String(c?.canonical?.display_name||c?.canonical?.name||c?.display_name||c?.name||fallback)}
function assetOf(c){const id=String(c?.character_id||"").trim();if(!id)return"";const v=c?.canonical?.visual||{};return String(v.card_hd_url||v.card_url||v.avatar_url||"./assets/production/cards/"+id+"--normal.jpg")}
function supportOf(id,getCharacter){return id?nameOf(getCharacter?.(id),String(id)):"EMPTY SLOT"}
export function buildHomeViewModel({snapshot=null,activeCharacter=null,roster=null,progression=null,getCharacter=null}={}){
 const s=snapshot&&typeof snapshot==="object"?snapshot:{},r=roster||s.roster||{activeBatter:null,supports:[null,null]},id=String(activeCharacter?.character_id||r.activeBatter||"").trim()||null,e=id?s.inventory?.characters?.[id]||null:null,p=progression&&typeof progression==="object"?progression:{},c=activeCharacter?.canonical||{},i=c.identity||{},stats=c.stats||{},supports=Array.isArray(r.supports)?[r.supports[0]||null,r.supports[1]||null]:[null,null];
 return {character:id?{id,name:nameOf(activeCharacter),rarity:String(c.rarity||"R").toUpperCase(),role:String(c.specialization||c.role||"UTILITY").toUpperCase(),position:String(c.position||"UNKNOWN").toUpperCase(),playIdentity:String(i.play_identity||c.play_identity||"PLAYSTYLE // UNKNOWN"),level:int(p.level,1),starRank:int(p.star_rank,0),duplicates:int(p.duplicate_count,Number(e?.quantity)||0),owned:Boolean(e?.unlocked&&Number(e?.quantity)>0),assetPath:assetOf(activeCharacter),stats:{power:int(stats.power),contact:int(stats.contact),speed:int(stats.speed)}}:null,roster:{activeBatterId:r.activeBatter||null,activeBatterName:id?nameOf(activeCharacter,id):"NO BATTER",supports:supports.map(x=>({id:x,name:supportOf(x,getCharacter),occupied:Boolean(x)}))},resources:{scrap:int(s.currencies?.SCRAP)},ownedCharacterCount:Object.values(s.inventory?.characters||{}).filter(x=>x?.unlocked&&Number(x?.quantity)>0).length}
}
export class HomeView{
 constructor({root=null,getSnapshot=()=>null,getActiveCharacter=()=>null,getRoster=()=>null,getProgression=()=>null,getCharacter=()=>null,onNavigate=null,onInspect=null}={}){Object.assign(this,{root,getSnapshot,getActiveCharacter,getRoster,getProgression,getCharacter,onNavigate,onInspect});this.model=null;this.bound=false}
 mount(){if(!this.root)return this;if(!this.bound){for(const b of this.root.querySelectorAll?.("[data-home-action]")||[]){b.addEventListener("click",()=>{const target=ACTION_TARGETS[b.dataset?.homeAction];if(target)this.onNavigate?.(target)})}this.root.querySelector?.("#home-character-detail-open")?.addEventListener("click",()=>{const id=this.model?.character?.id;if(id)this.onInspect?.(id)});this.bound=true}this.refresh();return this}
 getViewModel(){const c=this.getActiveCharacter?.(),s=this.getSnapshot?.()||null,r=this.getRoster?.()||s?.roster||null,p=c?.character_id?this.getProgression?.(c.character_id):null;return buildHomeViewModel({snapshot:s,activeCharacter:c,roster:r,progression:p,getCharacter:this.getCharacter})}
 refresh(){this.model=this.getViewModel();this.render(this.model);return this.model}
 text(sel,v){const e=this.root?.querySelector?.(sel);if(e)e.textContent=String(v??"")}
 render(m){if(!this.root)return;const c=m.character,has=Boolean(c);this.root.classList?.toggle("has-active-character",has);this.root.classList?.toggle("is-empty",!has);this.text("#home-character-name",has?c.name:"SIN PERSONAJE ACTIVO");this.text("#home-character-rarity",has?c.rarity:"RECLUTA PARA COMENZAR");this.text("#home-character-role",has?c.role+" • "+c.position:"ROSTER // VACÍO");this.text("#home-character-play-identity",has?c.playIdentity:"PLAYSTYLE // DESCONOCIDO");const detailButton=this.root.querySelector?.("#home-character-detail-open");if(detailButton){detailButton.disabled=!has;detailButton.hidden=false;}this.text("#home-character-level",has?"LV "+c.level:"LV --");this.text("#home-character-stars",has?"RANK "+c.starRank:"RANK --");this.text("#home-character-duplicates",has?"DUPLICATES ×"+c.duplicates:"DUPLICATES ×0");this.text("#home-stat-power",has?c.stats.power:"--");this.text("#home-stat-contact",has?c.stats.contact:"--");this.text("#home-stat-speed",has?c.stats.speed:"--");this.text("#home-squad-batter",m.roster.activeBatterName);this.text("#home-squad-support-0",m.roster.supports[0].name);this.text("#home-squad-support-1",m.roster.supports[1].name);this.text("#home-owned-count",m.ownedCharacterCount);this.text("#home-scrap",m.resources.scrap.toLocaleString("en-US"));const a=this.root.querySelector?.("#home-character-art"),e=this.root.querySelector?.("#home-character-empty");if(a){a.alt=has?c.name:"";a.hidden=!has;if(has&&c.assetPath&&a.src!==c.assetPath)a.src=c.assetPath;if(has){a.dataset.fallbackTried="false";a.onerror=()=>{if(a.dataset.fallbackTried!=="true"){a.dataset.fallbackTried="true";a.src="./assets/production/sprites/"+c.id+"_idle.png";return}a.hidden=true;if(e)e.hidden=false}}}if(e)e.hidden=has}
}
export const HOME_ACTION_TARGETS=ACTION_TARGETS;
