import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
const root=path.resolve("webapp");
const index=fs.readFileSync(path.join(root,"index.html"),"utf8");
const css=fs.readFileSync(path.join(root,"css/styles.css"),"utf8");
const panel=fs.readFileSync(path.join(root,"js/roster_panel.js"),"utf8");
const app=fs.readFileSync(path.join(root,"js/app.js"),"utf8");
const sw=fs.readFileSync(path.join(root,"sw.js"),"utf8");
assert.ok(index.includes('id="roster-panel"'));
assert.ok(index.includes('id="roster-panel-grid"'));
assert.ok(index.includes('id="roster-panel-set-active"'));
assert.ok(css.includes(".roster-panel") && css.includes(".roster-unit-card") && css.includes(".roster-detail"));
assert.ok(panel.includes("getInventory") && panel.includes("onSetActive"));
assert.ok(app.includes("rosterPanel.open()"));
assert.ok(app.includes("teamManager.setActiveBatter(characterId)"));
assert.ok(app.includes("stats: effectiveStats"));
assert.ok(sw.includes("./js/roster_panel.js"));
console.log("✅ P18 Roster: panel, collection grid, detail stats and active batter integration validated.");
